-- Demo schema for Alkyon. Covers the metadata endpoints (schemas, PKs, defaults,
-- views) and the type mapping (numeric, uuid, jsonb, timestamptz, bytea, arrays),
-- with enough rows that a streamed SELECT spans several batches.

CREATE SCHEMA sales;

CREATE TABLE sales.customer (
    id          integer      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id uuid         NOT NULL DEFAULT gen_random_uuid(),
    name        varchar(120) NOT NULL,
    country     char(2),
    credit      numeric(18,2) NOT NULL DEFAULT 0,
    tags        text[],
    metadata    jsonb,
    created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE sales.order_line (
    order_id    bigint      NOT NULL,
    line_no     smallint    NOT NULL,
    customer_id integer     NOT NULL REFERENCES sales.customer (id),
    sku         text        NOT NULL,
    quantity    integer     NOT NULL,
    unit_price  numeric(12,4) NOT NULL,
    shipped_on  date,
    signature   bytea,
    PRIMARY KEY (order_id, line_no)
);

CREATE VIEW sales.order_value AS
SELECT l.order_id,
       c.name AS customer,
       SUM(l.quantity * l.unit_price) AS total
FROM sales.order_line l
JOIN sales.customer c ON c.id = l.customer_id
GROUP BY l.order_id, c.name;

INSERT INTO sales.customer (name, country, credit, tags, metadata)
SELECT 'Customer ' || n,
       CASE n % 3 WHEN 0 THEN 'BE' WHEN 1 THEN 'FR' ELSE NULL END,
       (n * 13.37)::numeric(18,2),
       ARRAY['tier-' || (n % 4), 'seed'],
       jsonb_build_object('seq', n, 'active', n % 5 <> 0)
FROM generate_series(1, 250) AS n;

INSERT INTO sales.order_line (order_id, line_no, customer_id, sku, quantity, unit_price, shipped_on, signature)
SELECT 1000 + (n / 6),
       (n % 6)::smallint,
       1 + (n % 250),
       'SKU-' || lpad((n % 90)::text, 4, '0'),
       1 + (n % 7),
       (9.99 + (n % 40))::numeric(12,4),
       CASE WHEN n % 4 = 0 THEN NULL ELSE DATE '2025-01-01' + (n % 300) END,
       CASE WHEN n % 10 = 0 THEN decode(md5(n::text), 'hex') END
FROM generate_series(0, 1499) AS n;

ANALYZE;
